name: "Build Server and Push to ECR"
description: "Builds a Docker image, tags it and pushes to ECR"
inputs:
  targets:
    description: "List of targets to build, and repositories to push them"
    required: true
  build-args:
    description: "JSON with build args to pass to Docker"
    required: false
  disable-buildkit:
    description: "Disable Docker Buildkit"
    required: true
    default: "false"
  tag-prefix:
    description: "Add a prefix to the image tag"
    required: true
    default: ""
  dockerfile:
    description: "Path to Dockerfile"
    required: true
    default: "Dockerfile"
runs:
  using: "node16"
  main: "dist/index.js"
