name: 'Build Server and Push to ECR'
description: 'Builds a Docker image, tags it and pushes to ECR'
inputs:
  awsAccessKeyId:
    description: 'AWS Access Key ID'
    required: true
  awsSecretAccessKey:
    description: 'AWS Secret Access Key'
    required: true
  awsRegion:
    description: 'AWS Region'
    required: true
  ecrRegistry:
    description: 'ECR Registry'
    required: true
  ecrRepository:
    description: 'ECR Repository'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
